{ lib }:
{
  username = "zheng";
  userfullname = "Liu Jaanai";
  useremail = "liujaanai@gmail.com";
  networking = import ./networking.nix { inherit lib; };
  nixpkgs-config = import ./nixpkgs-config.nix { inherit lib; };

  # generated by `mkpasswd -m scrypt --rounds=11`
  # https://man.archlinux.org/man/crypt.5.en
  initialHashedPassword = "$7$GU..../....zPxyeBYmPbzdBM1sGr5KY.$KUbKAZmO3bQV7u52vpvKYGwgHaADqDqTNOTzeuXSeZ2";

  # Public Keys that can be used to login to all my PCs, Macbooks, and servers.
  #
  # Since its authority is so large, we must strengthen its security:
  # 1. The corresponding private key must be:
  #    1. Generated locally on every trusted client via:
  #      ```bash
  #      # KDF: bcrypt with 256 rounds, takes 2s on Apple M2):
  #      # Passphrase: digits + letters + symbols, 12+ chars
  #      ssh-keygen -t ed25519 -a 256 -C "ryan@xxx" -f ~/.ssh/xxx
  #      ```
  #    2. Never leave the device and never sent over the network.
  # 2. Or just use hardware security keys like Yubikey/CanoKey.
  sshAuthorizedKeys = [
    # The main ssh keys for daily usage
    # "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL8B31wZficBJy4Tli3w+C0hsa7uhsMlff43JF6PSYBe liujaanai@gmail.com"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL8B31wZficBJy4Tli3w+C0hsa7uhsMlff43JF6PSYBe zheng@lz-pc"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC/P3wcnTB34/GmfDNqObV85/OdmqvRKv0fooDOZr+cj zheng@lz-nb"
"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOZdkOnvmQOiFYyWsWKCY+yfXDGt8mdYq3jlOOyshDjW zheng@lz-wsl"
  ];
}
